spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: microservice1
          uri: lb://microservice1
          predicates:
            - Path=/cep
    locator:
      enabled: true
      lower-case-service-id: true
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka