eureka:
  client:
    service-url:
      defaultZone: https://discovery-server-smai.onrender.com/eureka
      instance:
        hostname: discovery-server-smai.onrender
        instance-id: ${spring.application.name}:${instanceId:${random.value}}
server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: microservice1
          uri: lb://microservice1
          predicates:
            - Path=/cep
    locator:
      enabled: true
      lower-case-service-id: true